baseURL: "https://bespokelink.ae"
theme: "up-business-theme"
languageCode: "en-us"

title: " AI Voice"

googleAnalytics: "G-5539HT18TF"

summaryLength: 20

params:
  title: " AI-powered Voice Agents & PBX"
  description: "Our mission is to optimize workflows & untangle phone complexities!"
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"


  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "Dubai, UAE"
    - "Melbourne, Australia"
  #  - "New York, USA" 

  contact:
    - "team@bespokelink.ae"
    - "UAE +971 50 595 3127"
    - "AUS +613 9998 0490"
  #  - "USA +1 929 590 5907"

  copyright: "© 2025 Bespokelink Limited, LLC. All rights reserved."

menus:
  main:
    - name: ""
      url: "/#hero"
      weight: 1

  #  - name: "Services"
  #    url: "/services"
  #    weight: 2

  #  - name: "How it works"
  #    url: "/backend"
  #    weight: 3

  #  - name: "About"
  #    url: "/about-us"
  #    weight: 4

#    - name: "Blog"
#      url: "/blog"
#      weight: 5

  buttons:
    - name: "Start for free"
      url: "https://forms.zohopublic.com/bespokelink1/form/TrialRequest/formperma/nRKlkfG2IjyRTpgMsiEgGMb75k4IFnD7eMLQQmhVf_U"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Services"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

#    - name: "Pricing"
#      url: "/#"
#      weight: 4

    - name: "Resources"
      url: "/resources"
      weight: 5

#    - name: "Blog"
#      url: "/blog"
#      weight: 6


taxonomies:
  series: "series"
  tags: "tags"
